### ISSUE TITLE
ResourcesNotFoundException

### ISSUE THREAD

**Issue by GauravCreed** [MrBIMC/MaterialDesignIcons#1]
hi @MrBIMC 

i am using **zzz_camera_switch drawable** in my code and test it will working perfectly in my phone but whenever i try to test in my tablet that time it will generate ResourcesNotFoundException i don't know why this is happening can u please help me to solve this issue..?

My error log like..

`06-17 12:46:23.292: E/AndroidRuntime(15651): FATAL EXCEPTION: main
06-17 12:46:23.292: E/AndroidRuntime(15651): Process: jp.co.cyberagent.android.gpuimage.sample, PID: 15651
06-17 12:46:23.292: E/AndroidRuntime(15651): java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.co.cyberagent.android.gpuimage.sample/com.example.main.ActivityCamera}: android.content.res.Resources$NotFoundException: File res/drawable/zzz_camera_switch.xml from drawable resource ID #0x7f0200dc
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2247)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.ActivityThread.access$800(ActivityThread.java:139)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.os.Handler.dispatchMessage(Handler.java:102)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.os.Looper.loop(Looper.java:136)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.ActivityThread.main(ActivityThread.java:5028)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at java.lang.reflect.Method.invokeNative(Native Method)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at java.lang.reflect.Method.invoke(Method.java:515)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at dalvik.system.NativeStart.main(Native Method)
06-17 12:46:23.292: E/AndroidRuntime(15651): Caused by: android.content.res.ResourcesNotFoundException: File res/drawable/zzz_camera_switch.xml from drawable resource ID #0x7f0200dc
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.content.res.Resources.loadDrawable(Resources.java:2149)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.content.res.MiuiResources.loadDrawable(MiuiResources.java:393)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.content.res.Resources.loadDrawable(Resources.java:2072)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.content.res.Resources.getDrawable(Resources.java:710)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:321)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at com.example.main.ActivityCamera.onCreate(ActivityCamera.java:1147)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.Activity.performCreate(Activity.java:5241)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
06-17 12:46:23.292: E/AndroidRuntime(15651):    ... 11 more
06-17 12:46:23.292: E/AndroidRuntime(15651): Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag vector
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:935)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:879)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.content.res.Resources.createFromXml(Resources.java:2525)
06-17 12:46:23.292: E/AndroidRuntime(15651):    at android.content.res.Resources.loadDrawable(Resources.java:2145)
06-17 12:46:23.292: E/AndroidRuntime(15651):    ... 19 more
06-17 12:46:25.064: E/ActivityThread(960): Failed to find provider info for com.miui.networkassistant.provider
06-17 12:46:25.182: E/octvm_drv(1708): common drv: platform_autosave_handle -> not implemented
: E/(): Device disconnected
`

Thanks

**Comment by MrBIMC** [comment]
What android version is your tablet runs on?

**Comment by GauravCreed** [comment]
hi @MrBIMC 

Thanks for the response, I currently using Xiaomi - Mi Pad Tablet  (4.4)

**Comment by MrBIMC** [comment]
Well, for me it works on all devices I tested (4.0, 4.1, 4.4, 5.0, 6.0, 7.0), so it's kinda weird. 

Try making clean/build. Should work.

**Comment by GauravCreed** [comment]
Hey @MrBIMC 

Thanks for the quick response,but i still getting this error in also Genymotion Devices  currently i am using **Google Galexy Nexus - 4.3 - Api 18 (780 \* 1280).** 

it will perfectly execute in all other devices like **5.0 , 5.1 etc..** 
Thanks.
