### ISSUE TITLE
ArrayIndexOutOfBoundsException Android 5.0

### ISSUE THREAD

**Issue by audiultx** [MrBIMC/MaterialDesignIcons#4]
**Hi, thanks for a great library, it has been really useful for me. 
just wanted to let you know that i am having problem with zzz_tag_multiple
i get this exception everytime. Its on a LG g3 android 5.0, seams to work fine on android 6.0 thou** 

```
ACRA caught a ArrayIndexOutOfBoundsException for "app"
10-07 15:56:30.549 E/ACRA    (32026): java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
10-07 15:56:30.549 E/ACRA    (32026):   at android.util.PathParser$PathDataNode.addCommand(PathParser.java:340)
10-07 15:56:30.549 E/ACRA    (32026):   at android.util.PathParser$PathDataNode.nodesToPath(PathParser.java:260)
10-07 15:56:30.549 E/ACRA    (32026):   at android.graphics.drawable.VectorDrawable$VPath.toPath(VectorDrawable.java:1265)
10-07 15:56:30.549 E/ACRA    (32026):   at android.graphics.drawable.VectorDrawable$VPathRenderer.drawPath(VectorDrawable.java:950)
10-07 15:56:30.549 E/ACRA    (32026):   at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:931)
10-07 15:56:30.549 E/ACRA    (32026):   at android.graphics.drawable.VectorDrawable$VPathRenderer.draw(VectorDrawable.java:938)
10-07 15:56:30.549 E/ACRA    (32026):   at android.graphics.drawable.VectorDrawable$VectorDrawableState.updateCachedBitmap(VectorDrawable.java:705)
10-07 15:56:30.549 E/ACRA    (32026):   at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
10-07 15:56:30.549 E/ACRA    (32026):   at android.widget.ImageView.onDraw(ImageView.java:1148)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:15148)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14082)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14077)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.widget.ListView.drawChild(ListView.java:3396)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.widget.AbsListView.dispatchDraw(AbsListView.java:2637)
10-07 15:56:30.549 E/ACRA    (32026):   at android.widget.ListView.dispatchDraw(ListView.java:3391)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:15151)
10-07 15:56:30.549 E/ACRA    (32026):   at android.widget.AbsListView.draw(AbsListView.java:4310)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14082)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14077)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14077)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:15151)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14082)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14077)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14077)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:14872)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.draw(View.java:15151)
10-07 15:56:30.549 E/ACRA    (32026):   at android.widget.FrameLayout.draw(FrameLayout.java:592)
10-07 15:56:30.549 E/ACRA    (32026):   at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2657)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.updateDisplayListIfDirty(View.java:14082)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.View.getDisplayList(View.java:14105)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
10-07 15:56:30.549 E/ACRA    (32026):   at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
```

**Comment by matemink** [comment]
I got the same error on API 21
Maybe it is because of this http://stackoverflow.com/a/33738463/1356124

**Comment by matemink** [comment]
Crash reproduced on icon R.drawable.zzz_more
Because one of coordinate has e- sign
(0.882L-3.05176e-4)

**Comment by audiultx** [comment]
Also **zzz_key_plus** does not work on an LG G2 Android 5.0
